# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# source "$HOME/.cargo/env"
# cargo install typos-cli
# typos -c typos.toml
# typos -c typos.toml -w

[files]
# skip these files
extend-exclude = ["*.nodes","*.torrent","*.sh","*.py","*.proto","*.json","*.conf","*.toml"]

[default.extend-words]
# don't correct these false positives
tpos = "tpos"
ba = "ba"
tne = "tne"
HD = "HD"
